import { spawn, spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdtempSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { startMockGateway } from './mock-gateway.mjs';
const require = createRequire(import.meta.url); const executable = require('electron');
const directory = mkdtempSync(join(tmpdir(), 'stomylos-preview-'));
const seed = spawnSync(executable, ['scripts/seed-ui.mjs', directory], { env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' }, encoding: 'utf8' });
if (seed.status !== 0) throw new Error(seed.stderr || seed.stdout);
const { server, endpoint } = await startMockGateway();
const env = { ...process.env, STOMYLOS_DATA_DIR: directory, STOMYLOS_TEST_ENDPOINT: endpoint };
delete env.ELECTRON_RUN_AS_NODE; delete env.ELECTRON_RENDERER_URL;
const child = spawn(executable, ['.'], { env, stdio: 'ignore' });
console.log(`Preview started with simulated replies and temporary data: ${directory}`);
child.once('error', error => { console.error(error.message); server.close(); process.exitCode = 1; });
child.once('exit', code => { server.close(); process.exitCode = code ?? 1; });
process.once('SIGINT', () => child.kill('SIGTERM'));
process.once('SIGTERM', () => child.kill('SIGTERM'));
