import { _electron as electron } from 'playwright-core';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import { checkWindowIcon } from './check-window-icon.mjs';
import { createHash } from 'node:crypto';
const require = createRequire(import.meta.url);
const version = JSON.parse(readFileSync('package.json', 'utf8')).version;
const selected = JSON.parse(readFileSync('tests/fixtures/selected-conversation.json', 'utf8'));
const selectedIds = ['model_01', 'model_02', 'model_03', 'model_04', 'model_05', 'model_07', 'model_08'];
const selectedModels = ['anthropic/claude-fable-5.1', 'xiaomi/mimo-v2.5-pro', 'anthropic/claude-sonnet-5', 'openai/gpt-6-astra', 'google/gemini-3.8-flash', 'bytedance-seed/seed-2-1-turbo', 'deepseek/deepseek-v4-pro-0813'];
const root = mkdtempSync(join(tmpdir(), 'stomylos-package-'));
const directory = join(root, 'data/io.github.oukeidos.stomylos');
mkdirSync(join(root, 'home/.stomylos'), { recursive: true, mode: 0o700 });
const seed = spawnSync(require('electron'), ['scripts/seed-ui.mjs', directory], { env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' }, encoding: 'utf8' });
if (seed.status !== 0) throw new Error(seed.stderr || seed.stdout);
const env = { ...process.env, HOME: join(root, 'home'), XDG_DATA_HOME: join(root, 'data') };
delete env.ELECTRON_RUN_AS_NODE; delete env.STOMYLOS_TEST_ENDPOINT; delete env.ELECTRON_RENDERER_URL; delete env.STOMYLOS_DATA_DIR; delete env.STOMYLOS_LIVE_VERIFY;
const sourceLauncher = process.argv.includes('--source-launcher');
const executablePath = resolve(sourceLauncher ? (process.env.STOMYLOS_VERIFY_LAUNCHER ?? 'run.sh') : (process.env.STOMYLOS_VERIFY_BUNDLE ?? 'release/linux-unpacked/stomylos'));
let app; const errors = []; let firstId; const draft = '  A draft kept across a packaged restart.\n한글 and spaces  ';
const report = { status:'running', directory, executablePath, sourceLauncher, errors, checks: [],
  applicationSha256: sourceLauncher ? null : createHash('sha256').update(readFileSync(join(executablePath, '../resources/app.asar'))).digest('hex') };
async function launch() {
  app = await electron.launch({ executablePath, env, chromiumSandbox: true, timeout: 20_000 });
  const page = await app.firstWindow(); page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('button', { name: 'Partner: Automatic' }).waitFor();
  report.checks.push({ nativeIcon: await checkWindowIcon(app, page) });
  const flags = await app.evaluate(({ app, BrowserWindow }) => ({ packaged: app.isPackaged, noSandbox: app.commandLine.hasSwitch('no-sandbox'), sandbox: BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences().sandbox }));
  assert.deepEqual(flags, { packaged: true, noSandbox: false, sandbox: true });
  return page;
}
async function close(page) {
  const process = app.process(); const exited = new Promise(resolve => process.once('exit', resolve));
  await page.evaluate(() => window.stomylos.command('close')); await exited; app = null;
}
try {
  let page = await launch();
  const snapshot = await page.evaluate(() => window.stomylos.command('snapshot'));
  firstId = snapshot.sessions.find(s => s.state !== 'ended').id;
  assert.equal(await app.evaluate(({ app }) => app.getVersion()), version);
  assert.equal(snapshot.settings.appVersion, version);
  assert.deepEqual(snapshot.characters.map(c => c.id), selectedIds);
  assert.deepEqual(snapshot.characters.map(c => c.model), selectedModels);
  assert.equal(snapshot.settings.keyPresent, false); assert.equal(snapshot.sessions.length, 3);
  assert.equal(snapshot.settings.development, false); assert.equal(snapshot.settings.dataPath, directory);
  assert.equal(existsSync(join(directory, 'backups')), false, 'Normal startup must not create version backups');
  const dummyKey = 'public-fixture-key-never-sent';
  writeFileSync(join(root, 'home/.stomylos/.env'), `OPENROUTER_API_KEY=${dummyKey}\n`, { mode: 0o600 });
  await page.evaluate(() => window.stomylos.command('refreshKey'));
  const withKey = await page.evaluate(() => window.stomylos.command('snapshot'));
  assert.equal(withKey.settings.keyPresent, true); assert.ok(!JSON.stringify(withKey).includes(dummyKey));
  writeFileSync(join(root, 'home/.stomylos/.env'), '# No key configured.\n');
  await page.evaluate(() => window.stomylos.command('refreshKey'));
  assert.equal((await page.evaluate(() => window.stomylos.command('snapshot'))).settings.keyPresent, false);
  report.checks.push('Normal path without startup backups exercised with isolated HOME/XDG; external key status without key exposure or requests');
  await page.getByRole('textbox', { name: 'Your message' }).fill(draft);
  await page.getByText('Draft saved', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Partner: Automatic' }).click();
  assert.equal(await page.getByRole('menuitemradio').count(), 8); await page.keyboard.press('Escape');
  assert.ok(await page.locator('header').evaluate(node => node.getBoundingClientRect().height) <= 64);
  assert.equal(await page.locator('main').getByRole('button', { name: /Request details|Starter renewal/ }).count(), 0);
  assert.equal(await page.locator('.dictation').count(), 0, 'No idle voice panel');
  assert.equal(await page.locator('aside').isVisible(), false, 'Library starts closed');
  await page.getByRole('button', { name: 'Show history' }).click();
  await page.getByRole('button', { name: 'Hide history' }).click();
  await close(page); report.checks.push('Packaged native worker/SQLite/lock launch, offline history and draft save');
  page = await launch(); assert.equal(await page.getByRole('textbox', { name: 'Your message' }).inputValue(), draft);
  assert.equal(await page.locator('aside').isVisible(), false, 'Collapsed history survives restart');
  await page.getByRole('button', { name: 'Conversation details', exact: true }).click();
  await page.getByRole('dialog', { name: 'Conversation details', exact: true }).waitFor();
  await page.getByRole('button', { name: /Request details/ }).click();
  await page.getByText('No model requests have been made for this chat.').waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Show history' }).click();
  mkdirSync('test-results', { recursive: true });
  await page.screenshot({ path: 'test-results/compact-packaged.png' });
  report.checks.push('Compact header/composer, contextual details and persistent history collapse verified in the actual package');
  const reloaded = await page.evaluate(id => window.stomylos.command('loadSession', { sessionId: id }), firstId);
  assert.equal(reloaded.session.draft, draft); assert.equal(reloaded.requests.length, 0);
  const frozen = JSON.parse(reloaded.session.chat_config);
  assert.equal(frozen.system_prompt, JSON.parse(readFileSync('src/main/runtime-config.json', 'utf8')).conversationPrompt);
  assert.equal(frozen.version, 'stomylos_conversation_v7');
  assert.equal(frozen.time_version, 'stomylos_time_context_v1');
  assert.equal(frozen.seed_template, selected.seed);
  assert.deepEqual(frozen.characters.map(c => c.id), selectedIds);
  await page.getByRole('button', { name: /What small part of your day would you like to keep/ }).first().click();
  await page.getByRole('button', { name: /Analysis details/ }).click();
  assert.equal(await page.locator('.analysis-unit').count(), 8);
  report.checks.push('Clean reopen preserves the same source ID and exact draft; saved analysis readable offline');
  assert.equal(existsSync(join(directory, 'backups')), false, 'Restart must not create backups');
  const schema = spawnSync(require('electron'), ['-e', "const Database=require('better-sqlite3');const db=new Database(process.argv[1],{readonly:true});console.log(db.pragma('user_version',{simple:true}));db.close();", join(directory, 'stomylos.sqlite3')], { env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' }, encoding: 'utf8' });
  assert.equal(schema.status, 0); report.schemaVersion = Number(schema.stdout.trim()); assert.ok(Number.isInteger(report.schemaVersion) && report.schemaVersion > 0);
  report.gpu = await app.evaluate(({ app }) => app.getGPUFeatureStatus());
  report.argv = await app.evaluate(() => process.argv);
  assert.deepEqual(errors, []); await close(page); report.status='passed';
  console.log(JSON.stringify({ status: 'passed', ...report }, null, 2));
} finally {
  mkdirSync('test-results', { recursive: true }); writeFileSync(process.env.STOMYLOS_VERIFY_REPORT ?? (sourceLauncher ? 'test-results/source-launcher-report.json' : 'test-results/package-report.json'), JSON.stringify(report, null, 2));
  await app?.close().catch(() => undefined);
  if (report.status === 'passed') rmSync(root, { recursive: true, force: true });
}
